<a href="https://colab.research.google.com/github/edaska/Stochastic_Processes_-_Optimization_in_Machine_Learning/blob/main/lab3/Stochastic_Processes_%26_Optimization_in_Machine_Learning_(Lab_3_Exercise_3).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1><b>Exercise 3</b></h1> <p align="justify">Consider a Markov chain (X<sub>n</sub>) on the state space <b>X</b>={1,2,…,8} with transition probability matrix:</p> <ul> <img src="https://raw.githubusercontent.com/netmode/Stochastic-Processes-and-Optimization-in-Machine-Learning-Lab/refs/heads/main/lab3/ex3.png"><img> <li>Classify the states of the chain into communication classes. Which classes are open and which are closed? Which states are transient and which are recurrent? You can use the <a href="https://setosa.io/markov/index.html#%7B%22tm%22%3A%5B%5B0.5%2C0.5%2C0%2C0%2C0%2C0%2C0%2C0%5D%2C%5B0.25%2C0.75%2C0%2C0%2C0%2C0%2C0%2C0%5D%2C%5B0.25%2C0.25%2C0%2C0.125%2C0.375%2C0%2C0%2C0%5D%2C%5B0%2C0%2C0.25%2C0%2C0.75%2C0%2C0%2C0%5D%2C%5B0%2C0%2C0.2%2C0.2%2C0.2%2C0.2%2C0.2%2C0%5D%2C%5B0%2C0%2C0%2C0%2C0%2C0%2C0.5%2C0.5%5D%2C%5B0%2C0%2C0%2C0%2C0%2C0.5%2C0%2C0.5%5D%2C%5B0%2C0%2C0%2C0%2C0%2C0.5%2C0.5%2C0%5D%5D%7D">simulator</a>, which has been appropriately configured for this exercise.</li> <li>Based on the answer of the previous question, find the stationary distribution of the Markov chain for the case where the chain starts from state (a) 1 and (b) 8.</li> <li>Examine the case where the chain starts from state 1. Suppose that at some step, the chain is in state 2 and that the transient phase has passed. What is the expected number of steps required for the chain to return to state 2 for the first time?</li> </ul>


In [1]:
import numpy as np
import pandas as pd

P = np.array([
    [1/2, 1/2, 0, 0, 0, 0, 0, 0],
    [1/4, 3/4, 0, 0, 0, 0, 0, 0],
    [1/4, 1/4, 0, 1/8, 3/8, 0, 0, 0],
    [0, 0, 1/4, 0, 3/4, 0, 0, 0],
    [0, 0, 1/5, 1/5, 1/5, 1/5, 1/5, 0],
    [0, 0, 0, 0, 0, 0, 1/2, 1/2],
    [0, 0, 0, 0, 0, 1/2, 0, 1/2],
    [0, 0, 0, 0, 0, 1/2, 1/2, 0],
])

print(P)


print(f"\nEach row should sum to 1:\n {P.sum(axis=1, keepdims=True)}")



df= pd.DataFrame(P)

sum_col = df.sum()

print(f"\n The sum of the elements in each column:\n {sum_col}")

[[0.5   0.5   0.    0.    0.    0.    0.    0.   ]
 [0.25  0.75  0.    0.    0.    0.    0.    0.   ]
 [0.25  0.25  0.    0.125 0.375 0.    0.    0.   ]
 [0.    0.    0.25  0.    0.75  0.    0.    0.   ]
 [0.    0.    0.2   0.2   0.2   0.2   0.2   0.   ]
 [0.    0.    0.    0.    0.    0.    0.5   0.5  ]
 [0.    0.    0.    0.    0.    0.5   0.    0.5  ]
 [0.    0.    0.    0.    0.    0.5   0.5   0.   ]]

Each row should sum to 1:
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]

 The sum of the elements in each column:
 0    1.000
1    1.500
2    0.450
3    0.325
4    1.325
5    1.200
6    1.200
7    1.000
dtype: float64


The chain has three communication classes:
{1,2}, {3,4,5}, and {6,7,8}.

States 1 and 2 communicate with each other and cannot leave this set, so {1,2} is a closed class.

States 3, 4, and 5 communicate with each other, but from state 5 the chain can move to states 6 or 7, so {3,4,5} is not closed.

States 6, 7, and 8 communicate with each other and transitions remain within this set, so {6,7,8} is also a closed class.

Transient States: These are the states in the open group {3, 4, 5} where the process will eventually leave and never return.

Recurrent States: These are the states in the closed groups {1, 2} and {6, 7, 8} that the process will return to with a probability of $1$.

*Based on the answer of the previous question, find the stationary distribution of the Markov chain for the case where the chain starts from state (a) 1 and (b) 8.*



(a) If we start in State 1, the process is trapped in the {1, 2} class. It will reach a stationary distribution strictly between states 1 and 2 (and the probabilities for states 3 through 8 will be $0$)


(b) If we start in State 8, the process is trapped in the {6, 7, 8} class. It will reach a completely different stationary distribution strictly between those three states.



To find the stationary probabilities ($\pi_1$ for State 1, and $\pi_2$ for State 2), we need to solve the formula is $\pi = \pi P$, combined with the normalization equation $\sum \pi_i = 1$.

Let's write out the system of linear equations based on our 2x2 matrix:

Equation for State 1: $\pi_1 = \frac{1}{2}\pi_1 + \frac{1}{4}\pi_2$

Equation for State 2: $\pi_2 = \frac{1}{2}\pi_1 + \frac{3}{4}\pi_2$

Normalization Equation: $\pi_1 + \pi_2 = 1$

In [2]:
# (a) 1

P = np.array([
    [1/2, 1/2],
     [1/4, 3/4],
])

print(P)

print(f"\nEach row should sum to 1:\n {P.sum(axis=1, keepdims=True)}")

#state 1
pi = np.array([[1/2, -1/4],
              [1, 1],])

b = np.array([[0],
              [1],])

x = np.linalg.solve(pi, b)

print("\nYour stationary distribution is:")
print(x)


[[0.5  0.5 ]
 [0.25 0.75]]

Each row should sum to 1:
 [[1.]
 [1.]]

Your stationary distribution is:
[[0.33333333]
 [0.66666667]]


Let's write out the system of linear equations based on our 3x3 matrix:

Equation for State 6: $\pi_6 = \frac{1}{2}\pi_7 + \frac{1}{2}\pi_8$

Equation for State 7: $\pi_7 = \frac{1}{2}\pi_6 + \frac{1}{2}\pi_8$

Equation for State 8: $\pi_8 = \frac{1}{2}\pi_6 + \frac{1}{2}\pi_7$

Normalization Equation: $\pi_6 + \pi_7 + \pi_8 = 1$

In [3]:
# (b) 8

P = np.array([
    [0, 1/2, 1/2],
    [1/2, 0, 1/2],
    [1/2, 1/2, 0],
])

print(P)

print(f"\nEach row should sum to 1:\n {P.sum(axis=1, keepdims=True)}")

#state 1
pi = np.array([[1, -1/2, -1/2],
               [-1/2, 1, -1/2],
              [1, 1, 1],])

b = np.array([[0],
              [0],
              [1],])

x = np.linalg.solve(pi, b)

print("\nYour stationary distribution is:")
print(x)


[[0.  0.5 0.5]
 [0.5 0.  0.5]
 [0.5 0.5 0. ]]

Each row should sum to 1:
 [[1.]
 [1.]
 [1.]]

Your stationary distribution is:
[[0.33333333]
 [0.33333333]
 [0.33333333]]


The Final Result for our stationary distribution for (a) is:

$\pi = [\frac{1}{3}, \frac{2}{3}]$

for (b):

$\pi = [\frac{1}{3}, \frac{1}{3}, \frac{1}{3}]$


*Examine the case where the chain starts from state 1. Suppose that at some step, the chain is in state 2 and that the transient phase has passed. What is the expected number of steps required for the chain to return to state 2 for the first time?*



We found previously that the ${π}_2 = \frac{2}{3}$. We also know that, averaged on $𝑘$, $E[{T}_i(k)]$ is inversely proportional to the relative occurrence of state 𝑖 in an infinite horizon, identified as the Steady State Probabilities with ${π}_i = \frac{1}{E[{T}_i(k)]}$.
So, if make the calculations we will find that $E[{T}_2]=\frac{3}{2}$, which are the expected number of steps required for the chain to return to state 2 for the first time.